import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });
const poppins = localFont({
  src: [
    {
      path: "./fonts/Poppins-Thin.woff",
      weight: "100",
    },
    {
      path: "./fonts/Poppins-Light.woff",
      weight: "300",
    },
    {
      path: "./fonts/Poppins-Regular.woff",
      weight: "400",
    },
    {
      path: "./fonts/Poppins-Medium.woff",
      weight: "500",
    },
    {
      path: "./fonts/Poppins-Bold.woff",
      weight: "700",
    },
    {
      path: "./fonts/Poppins-Black.woff",
      weight: "900",
    },
  ],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>{children}</body>
    </html>
  );
}
